// Generated by CoffeeScript 1.6.3
(function() {
  var winston;

  winston = require('winston');

  module.exports = function(options) {
    return function(i18n) {
      return i18n.logger.add(winston.transports.Console, options);
    };
  };

}).call(this);
